# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tach}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["geemus (Wesley Beary)"]
  s.date = %q{2010-04-07}
  s.description = %q{Shotgun benchmarking with noticeable progress and pretty results.}
  s.email = %q{wbeary@engineyard.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitignore",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/tach.rb",
    "tests/tach_tests.rb",
    "tests/tests_helper.rb"
  ]
  s.homepage = %q{http://github.com/geemus/tach}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Shotgun benchmarking}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<formatador>, [">= 0.0.12"])
      s.add_development_dependency(%q<shindo>, [">= 0"])
    else
      s.add_dependency(%q<formatador>, [">= 0.0.12"])
      s.add_dependency(%q<shindo>, [">= 0"])
    end
  else
    s.add_dependency(%q<formatador>, [">= 0.0.12"])
    s.add_dependency(%q<shindo>, [">= 0"])
  end
end

